### ISSUE TITLE
[Generator] Design prompts 

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/generator-jhipster-micronaut#1]
Design and decide the prompts. 

* What are the applications we will be supporting ?
    - Monolith
    - Microservices 
    - UAA

* Databases to support

* Caching to support

* authentication to support

Based on the above decisions let us change the prompts.

**Comment by atomfrede** [comment]
I would keep it simple in the beginning. E.g.

* Monolith and Microservice
* PSQL, MySQL, Mongo(?) (and maybe go with testcontainers so no h2 for development)
* Caching no preference
* JWT, Oauth

**Comment by sendilkumarn** [comment]
I was even thinking just to have Monolith and SQL databases to start with  :)

**Comment by atomfrede** [comment]
Even better. But both jwt and oauth?

**Comment by sendilkumarn** [comment]
Yeah I want both of them, But will be really happy to hear from @graemerocher or @jameskleeh opinions before moving there.

**Comment by jameskleeh** [comment]
I'm not really sure what's being asked or the implications of an answer

**Comment by graemerocher** [comment]
We Probably need a bit more background. My knowledge of jhipster is short it seems :)

These would be the options the user is displayed when generating the app right? For databases we support configurations for a range of them but repositories for only SQL right now with Micronaut Data.

Caching we support Redis and Caffeine but will add more in 1.3

For security we support both JWT and OpenID Connect

**Comment by sendilkumarn** [comment]
@jameskleeh It directly translates to more work 😉  Can we set up a call, I will explain a bit on how JHipster works (~20 minutes)?

**Comment by jameskleeh** [comment]
Sure - I'm pretty flexible on EST. Just let me know when

**Comment by sendilkumarn** [comment]
Sure let us have it on tomorrow (7th Aug). 1400H EST ?

**Comment by jameskleeh** [comment]
@sendilkumarn Sounds good - shoot me an invite kleehj@objectcomputing.com

**Comment by sendilkumarn** [comment]
Done 👍

**Comment by JasonTypesCodes** [comment]
The project currently supports:
* Monolith projects
* JWT or OAuth 2.0 Authentication
* SQL Database Support
  * MySQL
  * PostgreSQL
  * H2
* Ehcache
* Maven or Gradle Build System
* Angular or React Client
* Protractor Tests

I've created Issues for a few others:
* Microservices (#43)
* MariaDB (#44)
* Caffeine (#46)
* Hazelcast (#47)
* Redis (#48)
* Infinispan (#50)
* MongoDB (#49)

I also created some discussion issues for:
* "Optional" Server Items (#54)
* Additional Testing Frameworks (#56)
