### ISSUE TITLE
Fix Production Config and thymeleaf translation support in tests

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/generator-jhipster-micronaut#11]
Solving a few latent issues (seems the prod config isn't quite right, getting a driver issue, also thymeleaf translation support wasn't working in the tests when I would think it ought to)

[Refer](https://github.com/jhipster/generator-jhipster-micronaut/pull/10#issuecomment-590968351)

**Comment by willbuck** [comment]
These have been solved by 
https://github.com/jhipster/generator-jhipster-micronaut/pull/10/commits/ea82d24016849e5042118509f15b8b7253824660
and 
https://github.com/jhipster/generator-jhipster-micronaut/pull/10/commits/6940af99038b522839f91d92ed20274afbdef5e5

Thanks for converting my task list to issues, good call!
