### ISSUE TITLE
Use the micronaut gradle plugin

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster-micronaut#113]
##### **Overview of the feature request**

To have minimal custom code and use best practices from latest micronaut development we should try to use the official gradle plugin. See https://github.com/micronaut-projects/micronaut-gradle-plugin

##### **Motivation for or Use Case**

Less jhipster specific code more standard micronaut code.

##### **Related issues or PR**

* https://github.com/jhipster/generator-jhipster-micronaut/issues/89
* https://github.com/jhipster/generator-jhipster-micronaut/pull/108

**Comment by JasonTypesCodes** [comment]
I'd like to leave a note here that the 2.1 release of micronaut will include a much improved Gradle plugin

**Comment by agilob** [comment]
@atomfrede  If you don't mind I could take a look at this over the weekend? Just waiting for version of 2.1.0 to be in repos. Better understanding might help me with the native image issue.

**Comment by atomfrede** [comment]
Sure please go ahead.
