### ISSUE TITLE
Builds are flaky 

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster-micronaut#116]
##### **Overview of the issue**

During development of https://github.com/jhipster/generator-jhipster-micronaut/pull/85 I often wondered why the CI build was failing as they worked locally. After restarting the build often some other configuration, which was green before failed.  

##### **Reproduce the error**

Make a minimal PR which will not have an impact on the generated code and see how ci goes (maybe).

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by JasonTypesCodes** [comment]
@atomfrede is this the error(s) you are seeing: https://github.com/jhipster/generator-jhipster-micronaut/issues/122 ?

If so, my apologies for duplicating this issue, but it may be better to stick with the one I created as it has stacktrace information in it.  If this one is different we should keep both.

**Comment by atomfrede** [comment]
Yes exactly. Let's close this one.
