### ISSUE TITLE
Generated link to User produces code that doesn't compile

### ISSUE THREAD

**Issue by agilob** [jhipster/generator-jhipster-micronaut#132]
```
relationship OneToMany {
     Blog{user(login)} to User
}
```

Will produce code that has setters on blog which uses `user.setBlog(this)` but user class doesn't have this setter and link in liquibase

**Comment by agilob** [comment]
Noting that ManyToMany works fine.

**Comment by atomfrede** [comment]
I think this is not supported. See https://www.jhipster.tech/managing-relationships/

Only `many-to-one` to the user and `many-to-many` or `one-to-one` where the other entity is the owner are allowed. Not sure if we prevent this in the main generator/jdl level. But for now I will close this as the scenario you describe is not supported. If you want something similar you can create a new intermediate entity (e.g. BlogAuthor) and relate this to the the user via `one-to-one` and relate the `BlogAuthor` via `OneToMany` to the blog.
