### ISSUE TITLE
Error with Feature-Policy header: Unrecognized feature: 'speaker'.

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-micronaut#146]
##### **Overview of the issue**

Create an app and deploy it to Heroku. You'll get an error in your browser console when it loads.

```
Error with Feature-Policy header: Unrecognized feature: 'speaker'.
```

This does not happen in development.

##### **Reproduce the error**

Create an app and deploy it to Heroku.

**Comment by atomfrede** [comment]
I will take a look. Very strange as we have the same csp as in the main generator.
