### ISSUE TITLE
Health Checks screen is missing translations

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-micronaut#147]
##### **Overview of the issue**

translation-not-found[health.indicator.compositeDiscoveryClient()]
translation-not-found[health.indicator.jdbc]

<img width="1272" alt="Screen Shot 2020-08-07 at 9 09 05 AM" src="https://user-images.githubusercontent.com/17892/89659946-dc865180-d88d-11ea-8eef-f1931b2d2662.png">

##### **Reproduce the error**

Create an app and navigate to Administration > Health Checks.

Local install was preferred but not found.
INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-micronaut at /Users/mraible/spacefan/node_modules/generator-jhipster-micronaut
INFO! No custom commands found within blueprint: generator-jhipster-micronaut at /Users/mraible/spacefan/node_modules/generator-jhipster-micronaut
INFO! Executing jhipster:info
##### **JHipster Version(s)**

```
space@0.0.1-SNAPSHOT /Users/mraible/spacefan
├── generator-jhipster@6.10.1 
└─┬ generator-jhipster-micronaut@0.3.6
  └── generator-jhipster@6.10.1  deduped

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "oauth2",
    "cacheProvider": "ehcache",
    "clientFramework": "angularX",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": true,
    "baseName": "space",
    "buildTool": "maven",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["en", "fr"],
    "messageBroker": false,
    "nativeLanguage": "en",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": ["protractor"],
    "websocket": false,
    "applicationType": "monolith",
    "packageName": "org.jhipster.space",
    "packageFolder": "org/jhipster/space",
    "jhipsterVersion": "6.10.1",
    "creationTimestamp": 1596811260196,
    "skipServer": false,
    "clientPackageManager": "npm",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "useSass": true,
    "embeddableLaunchScript": false,
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [
      {
        "name": "generator-jhipster-micronaut",
        "version": "0.3.6"
      }
    ],
    "blueprints": [
      {
        "name": "generator-jhipster-micronaut",
        "version": "0.3.6"
      }
    ],
    "herokuAppName": "micronaut-space",
    "herokuDeployType": "git",
    "herokuJavaVersion": "11",
    "useOkta": true,
    "oktaAdminLogin": "mraible@gmail.com",
    "oktaAdminPassword": "Password1"
  },
  "entities": ["SpaceEvent", "Mission"]
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity SpaceEvent {
  name String required,
  date LocalDate required,
  description TextBlob required,
  photo ImageBlob required,
  type SpaceEventType required
}
entity Mission {
  name String required,
  description String
}
enum SpaceEventType {
  Launch,
  Landing
}

relationship OneToOne {
  SpaceEvent{mission(name)} to Mission
}

paginate SpaceEvent with infinite-scroll
paginate Mission with pagination

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

git version 2.24.3 (Apple Git-128)

node: v12.16.3

npm: 6.14.5

yeoman: 3.1.1

yarn: 1.22.4

Docker version 19.03.8, build afacb8b

docker-compose version 1.25.5, build 8a1c60f6

INFO! Congratulations, JHipster execution is complete!

**Comment by JasonTypesCodes** [comment]
This is a bit bigger than I first assumed.  Basically what is happening is Micronaut is sending back Health indicators that have different keys than their SB counterparts and the key is what is used to look up the translation.  I think what I'm going to do is map those keys to the expected ones in the client rather than move all of the i18n stuff into our blueprint just for a few keys.

**Comment by atomfrede** [comment]
Fully agree. With the upcoming 7.x and the jhipster control center the admin screens will be gone from the generated client, so we should not invest much time anymore.
