### ISSUE TITLE
Decide on Databases to support

### ISSUE THREAD

**Issue by sendilkumarn** [jhipster/generator-jhipster-micronaut#15]

**Comment by willbuck** [comment]
Looking to get the conversation started on this issue now as well, so we know what we're doing next when we get there.

I believe we have varying levels of support via GORM for all of these databases, however that would assume users create their app with Groovy. I think we should probably have a discussion about whether to be targeting multiple source languages (our users primarily prefer Groovy I believe), but if the initial goal is just Java, we should be targeting things [Micronaut Data](https://micronaut-projects.github.io/micronaut-data/latest/guide/) supports, and while I'm pretty certain there are plans to support NoSQL there, currently we're supporting JPA / Hibernate and JDBC.

Given that, @graemerocher @jameskleeh @jdubois @sendilkumarn @atomfrede what would we like to see supported by this initial release? Is H2/ MySQL enough or should we be aiming to get most/all of the current SQL flavors like Maria, Postgres etc? What does the jhipster team see used most frequently?

**Comment by atomfrede** [comment]
As we plan to make psql the default database I would go with psql and micronaut data. Regarding the language I would say let's focus on java for now.

**Comment by graemerocher** [comment]
Agreed on both counts

**Comment by sendilkumarn** [comment]
Supporting multiple languages is a big pain and requires a lot of effort. So let us focus Java first. H2, PSQL and MySQL makes sense to start with. I agree 👍
