### ISSUE TITLE
H2 Database UI not available and Faker with Docker Compose

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-micronaut#168]
##### **Overview of the issue**

I recorded a screencast of my Micronaut + JHipster blog post and found a couple of issues:

1. H2 Database link doesn't work in menu - it results in a page not found error
2. Running `app.yml` with Docker Compose still has faker.js data, even though it's a `prod` environment

See [my demo script](https://github.com/oktadeveloper/okta-jhipster-micronaut-example/blob/main/demo.adoc) for the steps I followed. They're the same as the blog post, just condensed.

**Comment by atomfrede** [comment]
Faker in production is fixed. Regarding h2 console I need to look in more detail. The h2 console is a servlet we add to the servlet context in the main generator. As we use netty maybe that won't work. I think for reactive applications we also don't have a h2 console.

**Comment by atomfrede** [comment]
I think we can start the h2 webserver, it's just under a different port. So the menu item will open e.g. `localhost:8084` in a new window for example.
