### ISSUE TITLE
React Build Failing (Cannot find name 'Cheerio'.)

### ISSUE THREAD

**Issue by JasonTypesCodes** [jhipster/generator-jhipster-micronaut#180]
The React build seems to be failing in master due to the following:

```
ERROR  Failed to compile with 2 errors2:45:54 PM

 error  in /home/runner/work/generator-jhipster-micronaut/generator-jhipster-micronaut/sample-output/gradle-jwt-react/node_modules/@types/enzyme/index.d.ts

ERROR in /home/runner/work/generator-jhipster-micronaut/generator-jhipster-micronaut/sample-output/gradle-jwt-react/node_modules/@types/enzyme/index.d.ts(384,15):
TS2304: Cannot find name 'Cheerio'.

 error  in /home/runner/work/generator-jhipster-micronaut/generator-jhipster-micronaut/sample-output/gradle-jwt-react/node_modules/@types/enzyme/index.d.ts

ERROR in /home/runner/work/generator-jhipster-micronaut/generator-jhipster-micronaut/sample-output/gradle-jwt-react/node_modules/@types/enzyme/index.d.ts(732,69):
TS2304: Cannot find name 'Cheerio'.
```

https://github.com/jhipster/generator-jhipster-micronaut/blob/master/test-integration/samples/gradle-jwt-react.jdl

**Comment by atomfrede** [comment]
That's strange. Why did the PR pipeline pass?

**Comment by JasonTypesCodes** [comment]
I had the same question.  I ran the action again and it failed the same way the second time.  I haven't had the opportunity to dig any deeper yet.

**Comment by murdos** [comment]
The problem seems to be related to a dependency of jhipster: see https://github.com/jhipster/generator-jhipster/issues/12593

**Comment by atomfrede** [comment]
I see. Didn't see that issue. Good to know, so we'll wait for the 6.x fix.

**Comment by suraj-shingade** [comment]
I am stuck here, Any quick fix.

**Comment by atomfrede** [comment]
See https://github.com/jhipster/generator-jhipster/issues/12593#issuecomment-699449153 for a workaround
