### ISSUE TITLE
Switch Default Branch to 'main'

### ISSUE THREAD

**Issue by JasonTypesCodes** [jhipster/generator-jhipster-micronaut#191]
I've pushed a main branch up, but myself and @atomfrede do not have repository rights to change the default branch.

@sendilkumarn or @mraible, can one of you help us with this?

**Comment by mraible** [comment]
I don't see a settings tab, which means I don't have permission either.

**Comment by atomfrede** [comment]
Pascal gave me permission, I switched the default branch to main. All PRs are pointing to main now as far as I can see, so you need to update your forks/local projects.
