### ISSUE TITLE
Improve integration tests by including more entities configurations

### ISSUE THREAD

**Issue by murdos** [jhipster/generator-jhipster-micronaut#199]
##### **Overview of the feature request**

As shown with the last 2 issues I reported - https://github.com/jhipster/generator-jhipster-micronaut/issues/198 and https://github.com/jhipster/generator-jhipster-micronaut/issues/197 - the entity generator is not well tested.

We should test various options: service, relationship, pagination, different field types, ...
IMO we should pick some very relevant entity samples in main generator (https://github.com/jhipster/generator-jhipster/tree/main/test-integration/samples/.jhipster) such as `EntityWith*` and `FieldTest*` ones.

##### **Motivation for or Use Case**

Working generated code in various configurations.

##### **Related issues or PR**

https://github.com/jhipster/generator-jhipster-micronaut/issues/198
https://github.com/jhipster/generator-jhipster-micronaut/issues/197

**Comment by atomfrede** [comment]
As suggested by @JasonTypesCodes let's close this and add more concrete issues if needed.
