### ISSUE TITLE
ERROR! Invalid Version: latest when upgrading to 0.7.0

### ISSUE THREAD

**Issue by poornerd** [jhipster/generator-jhipster-micronaut#211]
##### **Overview of the issue**
When I try to upgrade: mhipster upgrade, I get this error.  (I used npm to update jhipster and mhipster)

✔ Checking for new blueprint versions
Looking for latest generator-jhipster-micronaut version...
0.7.0
ERROR! Invalid Version: latest
TypeError: Invalid Version: latest

##### **Reproduce the error**

When I try to upgrade: mhipster upgrade, I get this error.  (I used npm to update jhipster and mhipster)

##### **JHipster Version(s)**

```
eclass@0.0.1-SNAPSHOT /Users/bp/projects/eclass/eclass
├── generator-jhipster@6.10.4 
└─┬ generator-jhipster-micronaut@0.6.0
  └── generator-jhipster@6.10.4  deduped

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "clientFramework": "react",
    "serverPort": "8080",
    "serviceDiscoveryType": false,
    "skipUserManagement": false,
    "baseName": "eclass",
    "buildTool": "gradle",
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "enableHibernateCache": true,
    "enableSwaggerCodegen": false,
    "enableTranslation": true,
    "jhiPrefix": "jhi",
    "languages": ["de", "en"],
    "messageBroker": false,
    "nativeLanguage": "de",
    "prodDatabaseType": "postgresql",
    "searchEngine": false,
    "skipClient": false,
    "testFrameworks": [],
    "websocket": false,
    "applicationType": "monolith",
    "blueprints": [
      {
        "name": "generator-jhipster-micronaut",
        "version": "0.6.0"
      }
    ],
    "clientPackageManager": "npm",
    "clientTheme": "yeti",
    "clientThemeVariant": "primary",
    "creationTimestamp": 1606047180120,
    "dtoSuffix": "DTO",
    "embeddableLaunchScript": false,
    "jhipsterVersion": "6.10.4",
    "jwtSecretKey": "YourJWTSecretKeyWasReplacedByThisMeaninglessTextByTheJHipsterInfoCommandForObviousSecurityReasons",
    "packageName": "de.ideafab.dpma.eclass",
    "packageFolder": "de/ideafab/dpma/eclass",
    "skipServer": false,
    "useSass": true,
    "entitySuffix": "",
    "otherModules": [
      {
        "name": "generator-jhipster-micronaut",
        "version": "0.6.0"
      }
    ]
  },
  "entities": []
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
/**
 * eClass9_0_CC_de: Klassentabelle (Classification Class, CC)
 */
entity Classification (eclass_classifications) {
  /**
   * International Code Designator (0173-1 für eCl@ss)
   */
  supplier String maxlength(6),
  /**
   * Identifier + VersionNumber
   */
  idCC String maxlength(9) required unique,
  /**
   * Identifikator (eindeutig für Strukturelement: Klasse)
   */
  identifier String maxlength(6) required unique,
  /**
   * Versionsnummer der Klasse
   */
  versionNumber Integer,
  /**
   * Tag der Versionserstellung
   */
  versionDate LocalDate,
  /**
   * Änderungsnummer der Klasse
   */
  revisionNumber Integer,
  /**
   * eCl@ss-Nummer
   */
  codedName String maxlength(8) required unique,
  /**
   * Bezeichnung der Klasse
   */
  prefferedName String maxlength(512),
  /**
   * Klassendefinition
   */
  definition String maxlength(1024),
  /**
   * Sprachcodierung nach ISO 639-1 / ISO 639-2, z.B. “de”
   */
  iSOLanguageCode String maxlength(2),
  /**
   * Landescodierung nach ISO 3166-1 / ISO 3166-2, z.B. “DE”
   */
  iSOCountryCode ISOCountryCode,
  /**
   * Anmerkung zur Definition
   */
  note String maxlength(1024),
  /**
   * Kommentar zur Verwendung der Klasse
   */
  remark String maxlength(1024),
  /**
   * Hierarchische Ebene
   */
  level Integer required,
  /**
   * Kennzeichen-Unterebene (0=nein/1=ja)
   */
  mKSubclass Boolean required,
  /**
   * Kennzeichen,ob der Klasse Schlagworte zugeordnet sind (0=nein/1=ja)
   */
  mKKeyword Boolean required,
  /**
   * Kennzeichen für Standardmerkmalleiste (2=Standardmerkmalleiste)
   */
  mKBSA Integer,
  /**
   * Primärschlüssel der Klasse; weltweit eindeutiger International Registration Data Identifier (Supplier+TypeOfSE+Identifier+VersionNumber)
   */
  irdiCC String maxlength(20) required unique
}
/**
 * eClass9_0_KWSY_de: Schlagwort- und Synonymtabelle (Keyword, KW; Synonym, SY)
 */
entity Keyword (eclass_keywords) {
  /**
   * International Code Designator des Schlagworts/Synonyms
   */
  supplierKW String maxlength(6),
  /**
   * Identifikator (eindeutig für Strukturelement: Schlagwort/Synonym)
   */
  identifier String maxlength(6) required,
  /**
   * Versionsnummer des Schlagworts / des Synonyms
   */
  versionNumber Integer,
  /**
   * Primärschlüssel der verbundenen Klasse / des verbundenen Merkmals
   */
  idCC String maxlength(9) required,
  /**
   * Bezeichnung des Schlagworts / des Synonyms
   */
  value String maxlength(80),
  /**
   * Beschreibung des Schlagworts / des Synonyms
   */
  explanation String maxlength(255),
  /**
   * Sprachcodierung nach ISO 639-1 / ISO 639-2, z.B. “de”
   */
  iSOLanguageCode String maxlength(2),
  /**
   * Landescodierung nach ISO 3166-1 / ISO 3166-2, z.B. “DE”
   */
  iSOCountryCode ISOCountryCode,
  /**
   * Identifier der Strukturelementart des Zieles (CC=Klasse, PR=Merkmal)
   */
  typeOfTargetSE EclassTypeOfTargetSE,
  /**
   * Primärschlüssel des Ziels; weltweit eindeutiger International Registration Data Identifier (Supplier+TypeOfSE+Identifier+VersionNumber)
   */
  irdiTarget String maxlength(20),
  /**
   * Primärschlüssel des Schlagworts/Synonyms; weltweit eindeutiger International Registration Data Identifier (Supplier+TypeOfSE+Identifier+VersionNumber)
   */
  irdiKW String maxlength(20) required,
  /**
   * Identifier der Strukturelementart (KW=Schlagwort, SY=Synonym). Anm.: Schlagworte (KW) können nur an Klassen, Synonyme (SY) können nur an Merkmale gehängt werden (siehe TypeOfTargetSE)
   */
  typeOfSE EclassTypeOfSE
}
/**
 * eClass9_0_PR_de: Merkmaltabelle (Property, PR)
 */
entity Attribute (eclass_attributes) {
  /**
   * International Code Designator (0173-1 für eCl@ss)
   */
  supplier String maxlength(6),
  /**
   * Identifier + VersionNumber
   */
  idPR String maxlength(9) required unique,
  /**
   * Identifikator (eindeutig für Strukturelement: Merkmal)
   */
  identifier String maxlength(6) required unique,
  /**
   * Versionsnummer des Merkmals
   */
  versionNumber Integer,
  /**
   * Tag der Versionserstellung
   */
  versionDate LocalDate,
  /**
   * Änderungsnummer des Merkmals
   */
  revisionNumber Integer,
  /**
   * Bezeichnung des Merkmals
   */
  prefferedName String maxlength(80),
  /**
   * Kurzbezeichnung des Merkmals
   */
  shortName String maxlength(17),
  /**
   * Merkmaldefinition
   */
  definition String maxlength(1024),
  /**
   * Quellenangabe zur Definition
   */
  sourceOfDefinition String maxlength(1024),
  /**
   * Anmerkung zur Definition
   */
  note String maxlength(1024),
  /**
   * Kommentar zur Verwendung des Merkmals
   */
  remark String maxlength(1024),
  /**
   * Bevorzugtes Formelzeichen
   */
  formularSymbol String maxlength(17),
  /**
   * Primärschlüssel der verbundenen Einheit; weltweit eindeutiger International Registration Data Identifier (Supplier+TypeOfSE+Identifier+VersionNumber)
   */
  irdiUN String maxlength(20),
  /**
   * Sprachcodierung nach ISO 639-1 / ISO 639-2, z.B. “de”
   */
  iSOLanguageCode String maxlength(2),
  /**
   * Landescodierung nach ISO 3166-1 / ISO 3166-2, z.B. “DE”
   */
  iSOCountryCode ISOCountryCode,
  /**
   * Typklasse des Merkmals nach IEC 61360
   */
  category String maxlength(3),
  /**
   * Kennzeichen für definierte Werteliste (direct= keine Werteliste definiert, freier Eintrag möglich; indirect= Auswahl aus definierter Werteliste)
   */
  attributeType EclassAttributeType,
  /**
   * Zuordnung zur ICS-Sachgruppenklassifikation
   */
  definitionClass String maxlength(255),
  /**
   * Datentyp des Merkmals (STRING | STRING_TRANSLATABLE | REAL_MEASURE | REAL_COUNT | REAL_CURRENCY | INTEGER_MEASURE | INTEGER_COUNT | INTEGER_CURRENCY | BOOLEAN | URL | RATIONAL | RATIONAL_MEASURE | TIME | TIMESTAMP | DATE), siehe 3.1.8
   */
  dataType EclassDataType,
  /**
   * Anzahl der Vorkommastellen (REAL_COUNT / REAL_MEASURE / REAL_CURRENCY / INTEGER_COUNT / INTEGER_MEASURE / INTEGER_CURRENCY)
   */
  digitsBeforeComma Integer,
  /**
   * Anzahl der Nachkommastellen (Real_COUNT / REAL_MEASURE / REAL_CURRENCY)
   */
  digitsAfterComma Integer,
  /**
   * Für Merkmale der Datentypen STRING / STRING_TRANSLATEABLE/ URL / RATIONAL / RATIONAL_MEASURE / TIME / TIMESTAMP / DATE spezifiziert es die max. Länge der Zeichenkette des Wertes. Für Merkmale der Datentypen URL / RATIONAL / RATIONAL_MEASURE / TIME / TIMESTAMP / DATE können Sonderzeichen enthalten sein
   */
  numberOfCharacters Integer,
  /**
   * Primärschlüssel des Merkmals; weltweit eindeutiger International Registration Data Identifier (Supplier+TypeOfSE+Identifier+VersionNumber)
   */
  irdiPR String maxlength(20) required,
  /**
   * Spezifiziert die Währung des Merkmals (INTEGER_CURRENCY, REAL_CURRENCY) nach ISO 4217, z.B. EUR, USD
   */
  currencyAlphaCode String maxlength(3)
}
enum ISOCountryCode {
  DE,
  US
}
enum EclassTypeOfTargetSE {
  CC (Klasse),
  PR (Merkmal)
}
enum EclassTypeOfSE {
  KW (Schlagwort),
  SY (Synonym)
}
enum EclassAttributeType {
  DIRECT,
  INDIRECT
}
enum EclassDataType {
  STRING,
  STRING_TRANSLATABLE,
  REAL_MEASURE,
  REAL_COUNT,
  REAL_CURRENCY,
  INTEGER_MEASURE,
  INTEGER_COUNT,
  INTEGER_CURRENCY,
  BOOLEAN,
  URL,
  RATIONAL,
  RATIONAL_MEASURE,
  TIME,
  TIMESTAMP,
  DATE
}

paginate Classification, Keyword, Attribute with pagination
service Classification, Keyword, Attribute with serviceClass

</pre>
</details>

##### **Environment and Tools**

java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

git version 2.29.2

node: v14.15.1

npm: 6.14.8

yeoman: 2.0.5

yarn: 1.22.10

Docker version 19.03.13, build 4484c46d9d

docker-compose version 1.27.4, build 40524192

identical .jhipster/Attribute.json
identical .jhipster/Classification.json
identical .jhipster/Keyword.json
INFO! Congratulations, JHipster execution is complete!

##### **Browsers and Operating System**

-   [ ] Checking this box is mandatory (this is just to show you read everything)

**Comment by JasonTypesCodes** [comment]
I was able to recreate this.  It may be something in the upstream generator. 
```
ERROR! Invalid Version: latest
TypeError: Invalid Version: latest
    at new SemVer (/home/jason/apps/node-v14.15.1-linux-x64/lib/node_modules/generator-jhipster-micronaut/node_modules/semver/classes/semver.js:41:13)
    at compare (/home/jason/apps/node-v14.15.1-linux-x64/lib/node_modules/generator-jhipster-micronaut/node_modules/semver/functions/compare.js:3:3)
    at Object.lt (/home/jason/apps/node-v14.15.1-linux-x64/lib/node_modules/generator-jhipster-micronaut/node_modules/semver/functions/lt.js:2:29)
    at /home/jason/apps/node-v14.15.1-linux-x64/lib/node_modules/generator-jhipster-micronaut/node_modules/generator-jhipster/generators/upgrade/index.js:271:44
    at new Promise (<anonymous>)
    at /home/jason/apps/node-v14.15.1-linux-x64/lib/node_modules/generator-jhipster-micronaut/node_modules/generator-jhipster/generators/upgrade/index.js:268:36
    at Array.map (<anonymous>)
    at module.exports.checkLatestBlueprintVersions (/home/jason/apps/node-v14.15.1-linux-x64/lib/node_modules/generator-jhipster-micronaut/node_modules/generator-jhipster/generators/upgrade/index.js:267:26)
    at Object.<anonymous> (/home/jason/apps/node-v14.15.1-linux-x64/lib/node_modules/generator-jhipster-micronaut/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:976:25)
    at /home/jason/apps/node-v14.15.1-linux-x64/lib/node_modules/generator-jhipster-micronaut/node_modules/run-async/index.js:49:25

```

I did a little console.log debugging and found that the version listed in the "blueprint" object indeed says "latest" even though in .yo-rc.json it clearly says 0.6.0

**Comment by liefra** [comment]
I'm getting the same error while trying to upgrade from version `0.8.0`(as it is in `.yo-rc.json`) to `1.0.1`. I have jHipster `6.10.5` installed. 

Here is the error on MacOS

```❯ mhipster upgrade
INFO! Using JHipster version installed globally
INFO! No custom sharedOptions found within blueprint: generator-jhipster-micronaut at /Users/liefra/data/management-system/node_modules/generator-jhipster-micronaut
INFO! No custom commands found within blueprint: generator-jhipster-micronaut at /Users/liefra/data/management-system/node_modules/generator-jhipster-micronaut
INFO! Executing jhipster:upgrade
Welcome to the JHipster Upgrade Sub-Generator
This will upgrade your current application codebase to the latest JHipster version
✔ Checking for new blueprint versions
Looking for latest generator-jhipster-micronaut version...
1.0.1
ERROR! Invalid Version: latest
TypeError: Invalid Version: latest
    at new SemVer (/usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/semver/classes/semver.js:41:13)
    at compare (/usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/semver/functions/compare.js:3:3)
    at Object.lt (/usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/semver/functions/lt.js:2:29)
    at /usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/generator-jhipster/generators/upgrade/index.js:271:44
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/generator-jhipster/generators/upgrade/index.js:268:36
    at Array.map (<anonymous>)
    at module.exports.checkLatestBlueprintVersions (/usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/generator-jhipster/generators/upgrade/index.js:267:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:976:25)
    at /usr/local/lib/node_modules/generator-jhipster-micronaut/node_modules/run-async/index.js:49:25```

**Comment by poornerd** [comment]
@liefra did you every get it working? I did not (also on MacOS).  Are you on an M1 Mac? (I am - I hope that does not make a difference)
