### ISSUE TITLE
Upgrade to JHipster 7

### ISSUE THREAD

**Issue by JasonTypesCodes** [jhipster/generator-jhipster-micronaut#250]
See: #233 

@atomfrede do you have a good feel for everything that is required for this move?

**Comment by atomfrede** [comment]
Not yet. Would try to generate an application with jhipster 7 and see what's working and what's not.

**Comment by mraible** [comment]
Added bug bounty to increase motivation. 😉

**Comment by kevintanhongann** [comment]
I assume the issue is done and merged?

**Comment by mraible** [comment]
Yes.

@mshima Please collect your bounty so we can close this issue.

**Comment by mshima** [comment]
Bounty claimed https://opencollective.com/generator-jhipster/expenses/89839.

**Comment by mshima** [comment]
I don't have permission to close the issue.

**Comment by DanielFran** [comment]
@mshima approved

**Comment by mshima** [comment]
@DanielFran thanks
