### ISSUE TITLE
Migrate to JHipster v8

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster-micronaut#288]
##### **Overview of the feature request**

JHipster v8 is getting close, we should migrate and make sure everything is working correctly.

Major tasks:
- [x] convert to esm
- [x] convert to integrated entities
- [x] migrate to angular 16
- [ ] move generator-jhipster server's enum files from server to java generator and drop custom enum write task
- [ ] move generator-jhipster server's domain (entity) files from server to java generator and drop custom enum write task
- [x] check generator-jhipster spring-data-relational's javax_persistence, hibernate_cache and maybe others integration

**Comment by mshima** [comment]
Is something missing for a new release?

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/177004.

**Comment by DanielFran** [comment]
@mshima approved
