### ISSUE TITLE
Docker build in Gradle project does not include the UI

### ISSUE THREAD

**Issue by JasonTypesCodes** [jhipster/generator-jhipster-micronaut#32]
In a Maven project, a docker build created following [these instructions](https://www.jhipster.tech/docker-compose/) will create a container that, when run, hosts the client application.  The Gradle build results in a container that does not host the client application

**Comment by atomfrede** [comment]
I can try to check in the coming days. Looking at the current config for maven I think the generated config for gradle is different. Can you post the generated `docker.gradle`?

**Comment by ZacharyKlein** [comment]
@atomfrede I'm not seeing a `docker.gradle` file in the generated project.

**Comment by atomfrede** [comment]
Ah then that's the problem I guess.

**Comment by ZacharyKlein** [comment]
@atomfrede I take that back - I was looking in a Maven project. 🤦  Here's what the `docker-gradle` file looks like in a Gradle project. I'm not seeing anything that strikes me as relevant to serving the UI, however.

```
jib {
    from {
        image = "adoptopenjdk:11-jre-hotspot"
    }
    to {
        image = "jhipstersampleapplication:latest"
    }
    container {
        entrypoint = ["bash", "-c", "chmod +x /entrypoint.sh && sync && /entrypoint.sh"]
        ports = ["8080"]
        environment = [
            SPRING_OUTPUT_ANSI_ENABLED: "ALWAYS",
            JHIPSTER_SLEEP: "0"
        ]
        creationTime = "USE_CURRENT_TIMESTAMP"
    }
}
```

**Comment by atomfrede** [comment]
Would agree with you. The base images differ from maven but won't make any difference

**Comment by atomfrede** [comment]
So maybe we have the same problem in the main generator :thinking:

**Comment by ZacharyKlein** [comment]
I am testing that hypothesis as we speak. :)
