### ISSUE TITLE
Dependabot auto-merge needs workflows status requirements

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster-micronaut#322]
##### **Overview of the issue**

PRs with auto-merge without requirements will be merged as soon as the PR is created

**Comment by mshima** [comment]
License should be dropped as requirement, dependabot doesn’t pass it

**Comment by mraible** [comment]
I updated the branch protection to remove `license/cla`. Below is a screenshot of what it is currently.

<img width="756" alt="Screenshot 2024-02-26 at 11 09 33 AM" src="https://github.com/jhipster/generator-jhipster-micronaut/assets/17892/55e01a0d-6785-46a9-a2ec-2ae73b567df6">
