### ISSUE TITLE
Error to create a micronaut application

### ISSUE THREAD

**Issue by javagrails** [jhipster/generator-jhipster-micronaut#329]
### **Error to create an Application using below commands**

**❯ mhipster** OR **❯ jhipster --blueprints micronaut**

ERROR! An error occured while running jhipster-micronaut:server#writeFiles
ERROR! ERROR! Template file src/main/java/package/config/dbmigrations/InitialSetupMigration.kt was not found at /Users/salehpc/.nvm/versions/node/v20.9.0/lib/node_modules/generator-jhipster-micronaut/generators/server/templates

### **Reproduce Environment and Bug Details in Picture**
❯ java --version
openjdk 21 2023-09-19
OpenJDK Runtime Environment (build 21+35-2513)
OpenJDK 64-Bit Server VM (build 21+35-2513, mixed mode, sharing)

❯ node --version
v20.9.0

❯ jhipster --version
8.2.1

❯ npm install -g generator-jhipster-micronaut

❯ mhipster --version
INFO! No custom commands found within blueprint: generator-jhipster-micronaut at /Users/salehpc/.nvm/versions/node/v20.9.0/lib/node_modules/generator-jhipster-micronaut
3.1.0 (generator-jhipster 8.2.1)

<img width="1700" alt="mh-prob-01" src="https://github.com/jhipster/generator-jhipster-micronaut/assets/3772814/d1eb31b9-792b-4f4c-92a1-23ad55f89312">

<img width="1752" alt="mh-prob-02" src="https://github.com/jhipster/generator-jhipster-micronaut/assets/3772814/fdd4de73-5af0-406b-ab74-49b0ead3b41f">

### **Suggest a Fix**
Have to look on any unwanted option aprear in application creation process, as @mraible guessing [Spring WebFlux] may be the problem as it is not Spring app it'a a Micronaut app

**Comment by mshima** [comment]
I will take a look at the generator-jhipster side.

**Comment by mraible** [comment]
@mshima It still prompts for the cache abstraction, which I believe should only be part of the main generator.

<img width="1442" alt="Screenshot 2024-04-01 at 5 07 23 PM" src="https://github.com/jhipster/generator-jhipster-micronaut/assets/17892/d2417797-9d25-4350-855e-53f85ccd791e">

As for the `jhipster-micronaut:server#writeFiles` error, that one is strange because it's trying to find a Kotlin file, rather than a Java one.

> ERROR! ERROR! Template file src/main/java/_package_/config/dbmigrations/InitialSetupMigration.kt was not found at /Users/mraible/dev/generator-jhipster-micronaut/generators/server/templates,/Users/mraible/dev/generator-jhipster-micronaut/node_modules/generator-jhipster/dist/generators/server/templates,/Users/mraible/dev/generator-jhipster-micronaut/node_modules/generator-jhipster/dist/generators/spring-data-relational/templates,/Users/mraible/dev/generator-jhipster-micronaut/node_modules/generator-jhipster/dist/generators/java/templates

There is a `InitialSetupMigration.java.ejs` file at [`generators/spring-data-mongodb/templates/src/main/java/_package_/config/dbmigrations/InitialSetupMigration.java.ejs`](https://github.com/jhipster/generator-jhipster/blob/main/generators/spring-data-mongodb/templates/src/main/java/_package_/config/dbmigrations/InitialSetupMigration.java.ejs).

**Comment by mshima** [comment]
Mongodb support never got finished.

**Comment by mraible** [comment]
The README says that NoSQL databases are not supported. How do I eliminate them from the choices? I tried the following, but it doesn't work.

```patch
diff --git a/generators/server/command.js b/generators/server/command.js
index 65a8071..0b1f965 100644
--- a/generators/server/command.js
+++ b/generators/server/command.js
@@ -1,7 +1,9 @@
 import { command as serverCommand } from 'generator-jhipster/generators/server';
+import { databaseTypes } from 'generator-jhipster/jdl';
 
-const { applicationType, ...remainingConfigs } = serverCommand.configs;
+const { applicationType, databaseType, ...remainingConfigs } = serverCommand.configs;
 
+const noSQL = [databaseTypes.MONGODB, databaseTypes.CASSANDRA, databaseTypes.COUCHBASE, databaseTypes.NEO4J];
 /**
  * @type {import('generator-jhipster').JHipsterCommandDefinition}
  */
@@ -13,6 +15,11 @@ const command = {
       ...applicationType,
       choices: applicationType.choices.filter(({ value }) => value !== 'gateway'),
     },
+    // NoSQL is not supported
+    databaseType: {
+      ...databaseType,
+      choices: databaseTypes.choices.filter(({ value }) => !noSQL.includes(value)),
+    },
     ...remainingConfigs,
   },
   override: true,
```

**Comment by mshima** [comment]
Not every option has been migrated to new config.

**Comment by mraible** [comment]
Fixed by https://github.com/jhipster/generator-jhipster-micronaut/pull/331.
