### ISSUE TITLE
Release 3.2.0 

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-micronaut#340]
Release v3.2.0 of this blueprint with JHipster 8.3.0 support.

**Comment by mraible** [comment]
@mshima @DanielFran Please let me know if anything else needs to be done before the release.

**Comment by DanielFran** [comment]
@mraible We should have some dependabot updates tomorrow morning, so it should be OK.

**Comment by mshima** [comment]
> @mraible We should have some dependabot updates tomorrow morning, so it should be OK.

@DanielFran I've triggered a dependabot run manually. So every dependabot dependency should be updated now.

But we should review prompts, it’s not importing some spring-boot prompts anymore.

**Comment by mraible** [comment]
I'll do a release tomorrow (Thursday) morning mountain time.

**Comment by mshima** [comment]
Micronaut 4.4.0 has been released https://github.com/jhipster/generator-jhipster-micronaut/pull/342.

**Comment by mraible** [comment]
@mshima A few of the jobs in #342 are failing with:

```
ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Can only be used in a Netty context
```

**Comment by mraible** [comment]
Done! https://github.com/jhipster/generator-jhipster-micronaut/releases/tag/v3.2.0
