### ISSUE TITLE
Rely on micronaut-* managed dependencies and move remaining dependencies to dependabot.

### ISSUE THREAD

**Issue by mshima** [jhipster/generator-jhipster-micronaut#349]
##### **Overview of the feature request**

https://github.com/jhipster/generator-jhipster-micronaut/blob/bc14f7353e3ad1de2779dbcf54833d9020b13835/generators/constants.cjs#L52-L71

https://github.com/jhipster/generator-jhipster-micronaut/blob/bc14f7353e3ad1de2779dbcf54833d9020b13835/generators/micronaut/templates/pom.xml.ejs#L123-L126

https://github.com/jhipster/generator-jhipster-micronaut/blob/bc14f7353e3ad1de2779dbcf54833d9020b13835/generators/micronaut/templates/pom.xml.ejs#L186

https://github.com/jhipster/generator-jhipster-micronaut/blob/bc14f7353e3ad1de2779dbcf54833d9020b13835/generators/micronaut/templates/build.gradle.ejs#L340

https://github.com/jhipster/generator-jhipster-micronaut/blob/bc14f7353e3ad1de2779dbcf54833d9020b13835/generators/micronaut/templates/gradle.properties.ejs#L53-L72

**Comment by mraible** [comment]
@mshima Do you want to do this before the next release (with JHipster 8.4.0), or wait until after?

**Comment by mshima** [comment]
@DanielFran bounty claimed https://opencollective.com/generator-jhipster/expenses/203366.
