### ISSUE TITLE
Release 3.3.0

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-micronaut#357]
Release v3.3.0 of this blueprint with JHipster 8.4.0 support.

**Comment by mraible** [comment]
@mshima @DanielFran Please let me know y'all think other issues need to be solved before this release.

**Comment by mshima** [comment]
No, please go ahead.

**Comment by DanielFran** [comment]
No problem too. You can go ahead with the new release

**Comment by mraible** [comment]
Fixed by https://github.com/jhipster/generator-jhipster-micronaut/releases/tag/v3.3.0. 

Tweet: https://twitter.com/jhipster/status/1780957505822089370
