### ISSUE TITLE
Add Microservice Project Support

### ISSUE THREAD

**Issue by JasonTypesCodes** [jhipster/generator-jhipster-micronaut#43]

**Comment by amanganiello90** [comment]
HI @JasonTypesCodes !! I will be happy to contribute to this project. 
So, this task requires only to enable microservice choise in the prompt questions avoiding client side?

**Comment by murdos** [comment]
No, I think it involves support for gateway and service discovery too.
FYI I was going to work on this subject too.

**Comment by amanganiello90** [comment]
Ok, so I pass to another issue. Thanks

**Comment by murdos** [comment]
A quick report of my progress, and what currently works:
- skipUserManagement and server-side skipClient (some adjustments will be required in regard to oauth2)
- microservice application type and related prompts
- service and distributed configuration with Consul (required some changes to jhipster/consul-config-loader: https://github.com/jhipster/consul-config-loader/pull/23)
- jwt authentification, with micronaut microservices decoding token generated and propagated by a jhipster/spring gateway

On my TODO:
- [ ] oauth2 authentification
- [ ] eureka service discovery
- [ ] spring cloud config server support
- [ ] exposing openapi of the microservice

**Comment by atomfrede** [comment]
:tada: wow! Thats great @murdos !

**Comment by atomfrede** [comment]
I think #188 closed this. Don't forget to claim your bounty @murdos, well deserved!
