### ISSUE TITLE
Question about status of project

### ISSUE THREAD

**Issue by amanganiello90** [jhipster/generator-jhipster-micronaut#6]
Hi all,
it is a beautiful project.. great! 
I would like to know the features supported from this blueprint and the status work progress. 
So I can contribute to this.
Thanks for the attention, good job!

**Comment by sendilkumarn** [comment]
The current work is happening at https://github.com/jhipster/jhipster-sample-app-micronaut

**Comment by amanganiello90** [comment]
Thanks
