### ISSUE TITLE
Support Consul

### ISSUE THREAD

**Issue by ZacharyKlein** [jhipster/generator-jhipster-micronaut#63]
This should be a simple add as Micronaut's Service Discovery client is very easy to configure against Consul. Just need to add the appropriate config when the feature is selected.

**Comment by murdos** [comment]
This ticket can be closed, support for Consul has been added while adding support for microservice: https://github.com/jhipster/generator-jhipster-micronaut/pull/188

**Comment by mraible** [comment]
Nice work, @murdos! I've added a bounty for this.
