### ISSUE TITLE
Java tests fail when selecting OAuth2

### ISSUE THREAD

**Issue by JasonTypesCodes** [jhipster/generator-jhipster-micronaut#66]
If entities have been generated, the EntityResourceIT tests fail to compile due to there not being a `TestSecurityConfiguration` class generated.

Otherwise, `JWTFilterTest.testJWTFilter` fails.

**Comment by mraible** [comment]
To provide some history, I found that I had to create a `TestSecurityConfiguration` to mock out the authorization server. You can read more about it [in this blog post](https://developer.okta.com/blog/2019/04/15/testing-spring-security-oauth-with-junit#how-to-handle-oidc-discovery-in-spring-boot-integration-tests).
