### ISSUE TITLE
Support Heroku deployment

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster-micronaut#82]
##### **Overview of the feature request**

I realized some configuration is spring specific (e.g. the build task for heroku), such that the build/deployment fails.

##### **Motivation for or Use Case**

One should be able to use `mhipster heroku` to deploy an application to Heroku with ease.

##### **Related issues or PR**

* https://github.com/jhipster/generator-jhipster-micronaut/issues/78

As I am right now on some heroku related things, I can take care of this. 

* [x] Make the heroku sub gene blueprint aware
* [ ] Adapt heroku files (gradle, properties) to micronaut

**Comment by atomfrede** [comment]
@JasonTypesCodes Just to make sure, is the gradle build supported to work? It seems it doesn't generate a valid executable jar file.

**Comment by JasonTypesCodes** [comment]
@atomfrede You know, I noticed that when I was adding workflows to the project and forgot to add an issue for it.  I'll add one now.

**Comment by JasonTypesCodes** [comment]
@atomfrede I'm curious why you labelled this issue as a bug?

**Comment by atomfrede** [comment]
Good question, at first I thought it was "bug" like some missing configuration, but there are a lot of more things to do also in the main generator. But good news, maven deploy works just fine with my current changes!
