### ISSUE TITLE
Update to Micronaut 2

### ISSUE THREAD

**Issue by JasonTypesCodes** [jhipster/generator-jhipster-micronaut#89]
##### **Overview of the feature request**

Once the Micronaut 2 RC1 release occurs, we should update the template to generate Micronaut 2 projects.

##### **Motivation for or Use Case**

Micronaut 2 rules!!

**Comment by atomfrede** [comment]
Thanks @mraible for putting the bounty. @JasonTypesCodes Should we share it, without your efforts it would not have been possible that fast?

**Comment by JasonTypesCodes** [comment]
@atomfrede That is very generous, but no.  You've done amazing work on this and absolutely deserve it.  Also, my job at OCI includes furthering and advancing Micronaut and Grails so all of my efforts are sponsored by OCI :smiley:

**Comment by atomfrede** [comment]
Thanks. Btw. I have experimented with graal native images. Maybe we can discuss that in the issue as I event can't get the minimal example via https://micronaut.io/launch/ up and running.

**Comment by JasonTypesCodes** [comment]
If you're having issues with Graal Native Images in Micronaut, an issue may be in order in the Micronaut org.  I would first suggest opening a discussion on the topic (https://github.com/micronaut-projects/micronaut-core/discussions/).  Are your problems related to, or similar to https://github.com/micronaut-projects/micronaut-core/discussions/3937 ?

**Comment by atomfrede** [comment]
I will do some more testing, I guess I am doing something wrong, although I basically tried to follow https://guides.micronaut.io/micronaut-creating-first-graal-app/guide/index.html but with maven.
