### ISSUE TITLE
Unable to run `mhipster` from public package

### ISSUE THREAD

**Issue by willbuck** [jhipster/generator-jhipster-micronaut#9]
Hey @sendilkumarn ! 

I tried installing this but it seemed as if just a `package.json` ended up in my global `node_modules/generator-jhipster-micronaut`, and no `mhipster` executable in my global `node/VERSION/bin`. After following the `contributing guidelines` instructions, I was able to build the repo and `npm link` it locally, but it seems like these instructions should probably be indicated in the base README.md file (instead of suggesting one to try using `mhipster` after a simple global install), would you agree?

Relatedly, I'm looking to help out in some capacity with development here! I'm fairly new to jhipster and the ecosystem at large, but my impression is that we'd want a `blueprint` for micronuat that replaces the spring boot backend in a typical jhipster generation, and not a "module". Is that accurate? Is this repo a "module" or a blueprint?

Where best can I begin adding templates for a base case app generation (say, perhaps, 

```
                    applicationType: 'monolith',
                    databaseType: 'sql',
                    devDatabaseType: 'h2Disk',
                    prodDatabaseType: 'mysql',
                    cacheProvider: 'ehcache',
                    authenticationType: 'jwt',
                    buildTool: 'gradle',
```

or whatever we deem to be a good "default micronaut app"?

**Comment by sendilkumarn** [comment]
My basic idea here is to revamp the prompts to only support the basic things and generate project with that (a simple basic server side only project) and then build from it

**Comment by JasonTypesCodes** [comment]
@willbuck is this issue still needed?

**Comment by willbuck** [comment]
No @JasonTypesCodes , it should have closed w/ my merged PR on Mar 6. My bad for missing that!
