### ISSUE TITLE
cleanup user service when using oauth

### ISSUE THREAD

**Issue by atomfrede** [jhipster/generator-jhipster-micronaut#94]
##### **Overview of the issue**

When selecting oauth option the `UserService` contains all methods (e.g. password reset etc.) which are not required. We should not generate them (like we do in main generator).

##### **Reproduce the error**

Generate an application with this blueprin.

##### **Related issues**

None

##### **Suggest a Fix**

Align with the template in main generator code

-   [x] Checking this box is mandatory (this is just to show you read everything)

**Comment by JasonTypesCodes** [comment]
I'm currently working through this as a part of #79

**Comment by atomfrede** [comment]
If I can help here let me know. In order to support okta we also need to have a function to sync the idp user with the [local user database](https://github.com/jhipster/generator-jhipster/blob/1a8536bef267b7dec18fe4b8051b59f25cad5575/generators/server/templates/src/main/java/package/service/UserService.java.ejs#L857). Basically thats why login via okta on heroku does not work yet.

**Comment by JasonTypesCodes** [comment]
Thanks!  I think I'm close.  Let me try to wrap it tonight and if I don't
make it I'll push up what I have and let you know where I'm at

**Comment by JasonTypesCodes** [comment]
@atomfrede I *thought* I was close, but I wasn't thinking about the generated tests.  I think once the generated tests are working on https://github.com/jhipster/generator-jhipster-micronaut/tree/issue-79-entity-related-user we will be in a good place.  If you'd like to take a look at that, please feel free.  Otherwise, I'll try to tackle it tomorrow.

**Comment by JasonTypesCodes** [comment]
@atomfrede I went ahead and did a merge of this portion to unblock you.  I'll resume #79 from here.  There were a lot of moving parts here.  Please let me know if you see something I missed

**Comment by atomfrede** [comment]
Going to test it. I have the micronaut 2 migration ready. Tested locally jwt + oauth. Need to check why the builds are still failing
